### PR TITLE
Added sorting ability, fixed tab bug.

### PR DESCRIPTION
**Pull request by Epicguru**
Adds the ability to sort achievement cards within a tab.
Currently achievements are listed in a consistent but rather arbitrary order (it's based on defName alphabetical sorting).

While this is fine for most achievements that are unrelated to each other, I wanted to add a way to sort my achievements without having to resort to renaming all my defs which would break existing saves and also is a hacky workaround to the problem.

AchievementTabDef.cs now looks like this:
``` C#
public class AchievementTabDef : Def
{
    public bool sorted;
}
```
If `<sorted>true</sorted>` is added to a TabDef then that tab will be sorted based on the following new field `order`:
``` C#
public class AchievementDef : Def
{
   public string texPath;
   public string bgtexPath;
    // ...
   public float order;
}
```

To re-iterate this has no effect on existing tabs and therefore no performance impact.
This simply allows me and others in future to sort our achievements, if necessary.

In this same PR I also fixed the following bug/oversight:
In `AchievementCard.cs` the `tab` field is only assigned to in the 'main' constructor:
``` C#
public AchievementCard(AchievementDef def, bool preUnlocked = false)
{
    tab = def.tab;
    if(tab is null)
    {
        tab = AchievementTabHelper.MainTab;
     }
}
```

This means that attempting to change the `<tab></tab>` node after the save file has been created does not actually result in it being changed tabs as expected, because the AchievementCard has already serialized the data and won't use `def.tab` again.

This has been corrected.

### CODE REVIEW

**Comment by Epicguru** [comment]
It's worth noting that the 'tab not updating' issue extends to the card system in general:

Since AchievementCard essentially makes a copy of the Tracker and then writes that in the save data, any changes made to the tracker in the AchievementDef won't be reflected in an existing save.
For example, say that I wanted to reduce the number of kills required to get an achievement. The player would have to start an entire new save for that updated kill requirement to take effect.

**Comment by SmashPhil** [comment]
> It's worth noting that the 'tab not updating' issue extends to the card system in general:
> 
> Since AchievementCard essentially makes a copy of the Tracker and then writes that in the save data, any changes made to the tracker in the AchievementDef won't be reflected in an existing save.
> For example, say that I wanted to reduce the number of kills required to get an achievement. The player would have to start an entire new save for that updated kill requirement to take effect.

This isn't entirely true.  Yes, cards are saved in-game w/ the trackers currently running them (this is because AchievementCards in general are generic and non descriptive of the things they are tracking ingame whereas trackers do track that data (and thus must save it as well).  The player can regenerate all cards if they want which will completely remove and remake the card (pulling any new changes you made).  This does not remove any previously locked cards but it does wipe clean any progress made on existing cards (cause again that data exists in the trackers which also need to be remade to pick up changes)

**Comment by Epicguru** [comment]
Okay I see, that makes sense.
If I understand correctly that means that a tracker can look for it's current card, and that card's AchievementDef will be the most up-to-date version?
I'll use that def to read the required number of kills then.

**Comment by SmashPhil** [comment]
Adding ordering is simple enough, I can just add it really quick.  There's really no need to add the IComparable interface as the achievement list can just be ordered directly.  It also doesn't need to determine sortability from the AchievementTabDef as having the same order number will result in the same ordering as if there was none at all.  

Also, I added the assigning of the tab from the def rather than saving it. Thinking back I honestly don't remember why I did it this way so it was indeed an oversight. It might've had to do with how the cards were originally set up and I just forgot about it entirely.  For future reference by the way (minor point) the ExposeData method implementation is called in 4 cases.

Saving
Loading
Resolving cross references
Post load initialization

So rather than having the assignment float freely in the method (letting it be assigned 4 separate times you could just specify to assign during post load init.  Not a huge deal but I also make the habit of specifying since sometimes it will matter (like with lists) and could result in exceptions being thrown

**Comment by SmashPhil** [comment]
> Okay I see, that makes sense.
> If I understand correctly that means that a tracker can look for it's current card, and that card's AchievementDef will be the most up-to-date version?
> I'll use that def to read the required number of kills then.

The trackers do store the required counts and do not immediately pick up changes from updates. This was a design choice and not an oversight.  I'm sorry if this inconveniences you but we will likely keep it this way

**Comment by Epicguru** [comment]
It's not too problematic, I'll just have to carefully balance achievement requirements before release.
Would you like me to make the changes to remove the interface and ExposdeData() or shall I leave it with you?
Thank you for your time!

**Comment by SmashPhil** [comment]
> It's not too problematic, I'll just have to carefully balance achievement requirements before release.
> Would you like me to make the changes to remove the interface and ExposdeData() or shall I leave it with you?
> Thank you for your time!

I got it, it's simple enough! I'll take a look at your other pull request

**Pull request closed without merging**
